name: Deploy ke cPanel

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, zip, exif, pcntl, gd, mysqli, pdo_mysql
          tools: composer:v2

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: 'presensi_karyawan'
          mysql user: 'laravel'
          mysql password: 'laravel'

      - name: Validasi composer.json dan composer.lock
        run: composer validate --strict

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Generate .env file dasar
        run: |
          echo "APP_KEY=base64:$(openssl rand -base64 32)" > .env
          # Konfigurasi untuk testing di GitHub Actions
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=presensi_karyawan" >> .env
          echo "DB_USERNAME=laravel" >> .env
          echo "DB_PASSWORD=laravel" >> .env

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Generate .env file lengkap
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          # Pastikan konfigurasi database tetap benar untuk GitHub Actions
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=presensi_karyawan" >> .env
          echo "DB_USERNAME=laravel" >> .env
          echo "DB_PASSWORD=laravel" >> .env

      - name: Migrasi Database
        run: |
          php artisan migrate --force

      - name: Optimasi Laravel
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan route:cache
          php artisan view:cache
          
      - name: Generate .env file untuk produksi
        run: |
          # Buat .env file untuk cPanel
          echo "${{ secrets.ENV_FILE }}" > .env
          # Ganti konfigurasi database untuk produksi
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_DATABASE=abdinega_abdira" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Deploy ke cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_ROOT_DIR }}/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            tests/**
            .github/**
            .env.example
            phpunit.xml
            README.md
