name: Deploy ke cPanel

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, zip, exif, pcntl, gd, mysqli, pdo_mysql
          tools: composer:v2

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: 'presensi_karyawan'
          mysql user: 'laravel'
          mysql password: 'laravel'
          mysql root password: 'root'
          # Meningkatkan max_allowed_packet dan wait_timeout untuk mencegah timeout
          mysql config: |
            max_allowed_packet=128M
            wait_timeout=3600
            interactive_timeout=3600

      - name: Konfigurasi akses MySQL untuk GitHub Actions
        run: |
          sleep 10 # Tunggu MySQL benar-benar siap
          mysql -h 127.0.0.1 -P 3306 -u root -proot -e "CREATE USER 'laravel'@'%' IDENTIFIED BY 'laravel';"
          mysql -h 127.0.0.1 -P 3306 -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'laravel'@'%' WITH GRANT OPTION;"
          mysql -h 127.0.0.1 -P 3306 -u root -proot -e "FLUSH PRIVILEGES;"

      - name: Validasi composer.json dan composer.lock
        run: composer validate --strict

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Siapkan .env sementara untuk composer install
        run: |
          echo "APP_KEY=base64:$(openssl rand -base64 32)" > .env
          echo "APP_ENV=testing" >> .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=:memory:" >> .env
          mkdir -p database
          touch database/database.sqlite

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-scripts

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'

      - name: Persiapan lingkungan Node.js
        run: |
          node --version
          npm --version
          npm install -g vite

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build assets
        run: NODE_ENV=production npm run build-ci
        continue-on-error: true
        
      - name: Build alternatif jika Vite gagal
        run: |
          echo "Menjalankan build alternatif untuk memastikan file yang diperlukan tersedia..."
          mkdir -p public/build
          # Salin file CSS dan JS jika ada
          if [ -d "resources/css" ]; then
            cp -r resources/css public/build/ || true
          fi
          if [ -d "resources/js" ]; then
            cp -r resources/js public/build/ || true
          fi
          # Buat manifest.json dasar jika belum ada
          if [ ! -f "public/build/manifest.json" ]; then
            echo '{"files":{"resources/css/app.css":{"file":"assets/app.css"},"resources/js/app.js":{"file":"assets/app.js"}}}' > public/build/manifest.json
          fi
          echo "Build alternatif selesai"

      - name: Menjalankan Laravel commands
        run: |
          php artisan key:generate
          php artisan config:cache
          php artisan route:cache
          php artisan package:discover --ansi

      - name: Generate .env file lengkap
        run: |
          # Buat temporary .env file dengan nilai-nilai utama
          cat > .env << EOL
          APP_KEY=base64:$(openssl rand -base64 32)
          APP_NAME="Sistem_Absensi_Sekolah"
          APP_ENV=production
          APP_DEBUG=false
          DB_CONNECTION=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=presensi_karyawan
          DB_USERNAME=laravel
          DB_PASSWORD=laravel
          CACHE_DRIVER=file
          QUEUE_CONNECTION=sync
          SESSION_DRIVER=file
          EOL

      - name: Migrasi Database dan Optimasi Laravel
        run: |
          # Periksa koneksi MySQL
          echo "Memeriksa koneksi MySQL..."
          if mysql -h 127.0.0.1 -P 3306 -u laravel -plaravel -e "SELECT 1" presensi_karyawan; then
            # Lakukan migrasi dengan MySQL
            echo "Koneksi MySQL berhasil, melakukan migrasi..."
            php artisan migrate --force --no-interaction
          else
            # Gunakan SQLite sebagai alternatif
            echo "Koneksi MySQL gagal, menggunakan SQLite..."
            echo "DB_CONNECTION=sqlite" > .env
            echo "DB_DATABASE=$(pwd)/database/database.sqlite" >> .env
            touch database/database.sqlite
            php artisan migrate --force --no-interaction
          fi
          
          # Optimasi Laravel tanpa database
          php artisan config:clear
          php artisan cache:clear
          php artisan route:cache
          # Skip view cache jika menyebabkan masalah
          # php artisan view:cache

      - name: Generate .env file untuk produksi
        run: |
          # Buat .env file untuk cPanel
          cat > .env << EOL
          APP_KEY=base64:$(openssl rand -base64 32)
          APP_NAME="Sistem_Absensi_Sekolah"
          APP_ENV=production
          APP_DEBUG=false
          DB_CONNECTION=mysql
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_DATABASE=abdinega_abdira
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          EOL

      - name: Deploy ke cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_ROOT_DIR }}/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            tests/**
            .github/**
            .env.example
            phpunit.xml
            README.md
