name: Deploy ke cPanel

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, zip, exif, pcntl, gd, mysqli, pdo_mysql
          tools: composer:v2

      - name: Validasi composer.json dan composer.lock
        run: composer validate --strict

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Generate .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Optimasi Laravel
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan route:cache
          php artisan view:cache

      - name: Deploy ke cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_ROOT_DIR }}/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            tests/**
            .github/**
            .env.example
            phpunit.xml
            README.md
